export function title(){
    let imgTitle = ['Serenity of the Mountains','Mystical Forest Pathway','Sunset by the Shore',' Tranquility by the Lake','Blossom Spring Meadow',' Peaceful Lakeside','Enchanted Forest','Glorrious Mountain Lake']

    return imgTitle;
}
export function content(){
    let content = ['Amidst the towering peaks, the crisp mountain air fills the soul with tranquility. The sun casts golden hues over the snow-capped summits, while a gentle breeze carries the whisper of rustling pine trees. This untouched wilderness stands as a testament to nature\'s raw beauty, inviting wanderers to lose themselves in its peaceful embrace.',
        'As the sun sets, the forest awakens with a mystical energy. The path ahead is shrouded in shadows, the trees whispering secrets of the night. The air is thick with the scent of damp earth and pine, and the soft glow of fireflies illuminates the darkness. The forest beckons, promising adventure and mystery to those who dare to wander its winding trails.',
        'The sun dips below the horizon, casting a warm glow over the tranquil shore. The gentle lapping of the waves against the sand creates a soothing melody, while the salty sea air fills the lungs with a sense of calm. Seagulls cry out overhead, their calls blending with the sound of the surf. The world seems to slow down, allowing for a moment of peace and reflection.',
        'The lake is a mirror, reflecting the sky above in perfect clarity. The water is still, save for the occasional ripple caused by a passing fish or gentle breeze. The air is filled with the scent of wildflowers and fresh water, and the sound of birdsong carries across the water. The world seems to hold its breath, waiting for the next moment of beauty to unfold.',
        'The meadow is alive with color, the vibrant blossoms swaying in the gentle breeze. The air is filled with the sweet scent of flowers and the sound of buzzing bees. The sun shines down, casting a warm glow over the landscape and inviting wanderers to bask in its golden light. The meadow is a place of peace and beauty, a sanctuary for the soul.',
        'The lake is a place of serenity, its waters calm and still. The sun sets in the distance, casting a warm glow over the landscape. The air is filled with the sound of crickets and the gentle lapping of the waves against the shore. The world seems to slow down, allowing for a moment of peace and reflection.',
        'The forest is alive with magic, its ancient trees towering overhead. The air is thick with the scent of damp earth and pine, and the sound of rustling leaves fills the air. Shafts of golden sunlight filter through the canopy, casting a warm glow over the forest floor. The world seems to hold its breath, waiting for the next moment of wonder to unfold.',
        'The mountain lake is a place of beauty and tranquility, its waters reflecting the towering peaks that surround it. The air is filled with the scent of pine and fresh water, and the sound of birdsong carries across the water. The sun sets in the distance, casting a warm glow over the landscape. The world seems to slow down, allowing for a moment of peace and reflection.'
        ]
        return content;
}